name: 🐛 Bug Report
description: Report a problem you encountered using SoldBy
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: What happened and what did you expect to happen? You can also attach a screenshot by dragging & dropping, selecting or pasting it in this field
      placeholder: I found a bug!
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Amazon Link
      description: Provide the link to the Amazon page where the problem occured, if it is crucial to the reproduction of the problem
      placeholder: https://www.amazon.com/gp/bestsellers/?ref_=nav_cs_bestsellers

  - type: input
    id: version
    attributes:
      label: SoldBy Version
      description: Which version of SoldBy are you using?
      placeholder: 1.4.0

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Opera
        - Brave
        - Other

  - type: dropdown
    id: manager
    attributes:
      label: Userscript manager
      description: Which userscript manager are you using?
      options:
        - Violentmonkey
        - Tampermonkey
        - Greasemonkey
        - Other
