name: 🐛 Bug Report
description: Report a problem you encountered using SoldBy
title: '🐛 '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: I found a bug!
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Are you using the latest version?
      description: Before submitting a bug report, please make sure you have updated to the [latest version of SoldBy](https://greasyfork.org/scripts/402064/code/script.user.js 'Update from greasyfork.org')
      options:
        - label: I am using the latest version available on greasyfork.org

  - type: dropdown
    attributes:
      label: Which browser?
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Opera
        - Brave
        - Other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Which userscript manager?
      options:
        - Violentmonkey
        - Tampermonkey
        - Greasemonkey
        - Other
    validations:
      required: true

  - type: input
    attributes:
      label: Link to the Amazon page where the problem occured
      description: Provide the link to the page, if it is crucial to the reproduction of the problem
      placeholder: e.g. https://www.amazon.com/gp/bestsellers/?ref_=nav_cs_bestsellers

  - type: textarea
    attributes:
      label: Screenshot
      description: If applicable, add a screenshot to help explain the problem
      placeholder: Attach files by dragging & dropping, selecting or pasting them ↩
